#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

\rm -rf case.foam contact history VTK normalContact_*.txt constant/polyMesh
\rm -rf processor0 processor1 processor2 processor3 processor4 processor5 processor6 processor7 processor8 processor9 processor10 processor11 processor12 processor13 processor14 processor15 processor16 processor17 processor18 processor19 processor20 processor21 processor22 processor23
\rm -rf log.decomposePar log.reconstructPar log.unsElasticSolidFoam